# Generated by Django 5.2.6 on 2025-09-27 03:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_rename_entry_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
